## Maven package
FROM quay.io/quarkus/centos-quarkus-maven:19.2.1 AS build

WORKDIR /project

# Download dependencies
RUN mkdir coffeeshop-service
COPY coffeeshop-service/pom.xml coffeeshop-service/
COPY pom.xml .
RUN mvn -f coffeeshop-service/pom.xml dependency:resolve

# Compile project
COPY coffeeshop-service/src/main/java coffeeshop-service/src/main/java
RUN mvn -f coffeeshop-service/pom.xml -Pnative package

COPY coffeeshop-service/src/main/resources coffeeshop-service/src/main/resources
RUN mvn -f coffeeshop-service/pom.xml -Pnative package

## Create Image
FROM registry.access.redhat.com/ubi8/ubi-minimal

WORKDIR /work/
COPY --from=build /project/coffeeshop-service/target/*-runner /work/application
RUN chmod 775 /work

EXPOSE 8080

CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dkafka.bootstrap.servers=kafka:9093", "-Dme.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://barista-http:8082"]
