apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffeeshopService.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: coffeeshop-service
    release: {{ .Release.Name }}
